# Generated by Django 4.0.4 on 2022-06-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bidder',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='user',
        ),
    ]
